### ISSUE TITLE
Base game tracks are not drawn on bridges

### ISSUE THREAD

**Issue by 2TallTyler** [EmperorJake/JPbridges#1]
![bridges](https://github.com/EmperorJake/JPbridges/assets/55058389/f1dd545b-5859-47e8-96f9-e461fdb15692)

This happens with base game sprites, including Iron Horse's extra rails (which use default graphics). Screenshot taken with JP+ Bridges as the only NewGRF loaded.

**Comment by EmperorJake** [comment]
This is partially intentional, as it's silly that bridge GRFs are forced to choose a single baseset rail or road graphic and bake it into the sprites. For this reason I mentioned in the description that it's "incompatible" with base railtypes and should be used with JapanSet tracks or any other railtype GRF.

Ideally, the game should instead layer baseset sprites over bridges if you're using a bridge GRF, the same way railtypes and roadtypes get layered if present. This is probably a limitation of the ancient bridge spec though, and I don't think that will change any time soon. I'm open to other potential solutions though

**Comment by 2TallTyler** [comment]
In that case, not a bug. 🙂
